"""add a bio and profile pic path to users table

Revision ID: 07d04be1e961
Revises: c22c322e1974
Create Date: 2021-09-19 11:46:47.937931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07d04be1e961'
down_revision = 'c22c322e1974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('biodata', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'biodata')
    # ### end Alembic commands ###
