"""update tables

Revision ID: 4156c1481571
Revises: 78c98d511fef
Create Date: 2021-09-20 12:57:08.462846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4156c1481571'
down_revision = '78c98d511fef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('downvotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pitch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upvotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pitch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('pitches', 'upvote')
    op.drop_column('pitches', 'downvote')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('downvote', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitches', sa.Column('upvote', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('upvotes')
    op.drop_table('downvotes')
    # ### end Alembic commands ###
