"""add submitted columns to pitches and comments

Revision ID: 6fe327a25870
Revises: 07d04be1e961
Create Date: 2021-09-19 16:20:30.751957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fe327a25870'
down_revision = '07d04be1e961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('submitted', sa.DateTime(), nullable=True))
    op.add_column('pitches', sa.Column('submitted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'submitted')
    op.drop_column('comments', 'submitted')
    # ### end Alembic commands ###
