"""Add a password column to User model

Revision ID: b7aeac2370d7
Revises: 7332772c4520
Create Date: 2021-09-19 00:31:27.108468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7aeac2370d7'
down_revision = '7332772c4520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_password')
    # ### end Alembic commands ###
